version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file event.yaml --s3-bucket repositoriocodepipeline --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - event.yaml
    - outputSamTemplate.yaml