AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Test Pipeline Lambda
Resources:
  hellofunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.7
      CodeUri: index.py
      Description: Sample SAM Lambda Deployment
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)